name: CI/CD

on:
  push:
    branches:
      - master

env:
  REGISTRY: andremart/flaskapp

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10'

      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "E501"
      

  build_and_push:
    runs-on: ubuntu-latest
    name: Build and push docker image
    needs: lint
    outputs:
      commit_hash: ${{ steps.commit_hash.outputs.commit_hash }}
    steps:

      - name: Git checkout
        uses: actions/checkout@v3

      - id: commit_hash
        run: echo "::set-output name=commit_hash::${GITHUB_SHA::7}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}:${{ steps.commit_hash.outputs.commit_hash }}

  deploy:
    strategy:
      matrix:
          server: [18.193.254.173, 3.74.47.14]
    runs-on: ubuntu-latest
    name: Deploy
    needs: build_and_push
    steps:

      - name: Mysql setup
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ matrix.server }}
          username: ${{ secrets.HOSTSUSERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            # Deleting old DB

            docker stop flask-app

            docker rm flask-app
            # Run mysql image and setup mysql
            docker run -d \
            --restart always \
            --name mysql_db \
            -p 3306:3306 \
            -v /var/lib/mysql:/var/lib/mysql \
            -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASS }} \
            -e MYSQL_USER=${{ secrets.DB_USER }} \
            -e MYSQL_PASSWORD=${{ secrets.DB_PASS }} \
            -e MYSQL_DATABASE=${{ secrets.DATABASE }} \
            -d mysql:8.0.29

      - name: Deploy to EC2 instanse via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ matrix.server }}
          username: ${{ secrets.HOSTSUSERNAME }}
          key: ${{ secrets.KEY }}
          envs: ${{ secrets.DOCKER_USER }}, ${{ secrets.DOCKERHUB_TOKEN }}
          port: 22
          script: |
            # login docker
            docker login -u $DOCKER_USER -p $DOCKERHUB_TOKEN

            docker stop flask-app

            docker rm flask-app

            # Run a new container from a new image
            docker run -d \
            --restart always \
            -p 5000:5000 \
            --name flask-app \
            ${{ env.REGISTRY }}:${{ needs.build_and_push.outputs.commit_hash }}
  
  curl:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: http://18.193.254.173:5000/api|http://3.74.47.14:5000/api